language: java
jdk:
  - oraclejdk8
sudo: required

before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/
cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/

# Matrix with linux configuration using gcc 5 as this is the version on the production machines
matrix:
  include:
  - os: linux

#before_install:
#- eval "${MATRIX_EVAL}"

#
install:
#- sudo rm -rf /usr/local/cmake*

# Run
before_script:
- ./gradlew clean assemble --stacktrace
script:
- ./gradlew test